version: '2'

services:
  Demo:
    build:
      context: ./../../build
      dockerfile: Dockerfile
      args:
        app_version: ${APP_VERSION}
    image: demo:${APP_VERSION}
    container_name: Demo
    ports:
      - "8080:8080"
      - "8081:8081"
      - "9875:9875"
# Uncomment to run locally using assumed (environment variable) credentials
#    environment:
#      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
#      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    env_file: env.properties
